### ISSUE TITLE
Not compatable with Phosphophyllite mod lib

### ISSUE THREAD

**Issue by Furious1964** [someaddons/performant_issues#114]
Loading screen hangs on first start and then crashes.

crashes when this mod is used.

** Mod version **
3.30m

[crash-2021-02-27_13.07.39-fml.txt](https://github.com/someaddons/performant_issues/files/6055092/crash-2021-02-27_13.07.39-fml.txt)

**Comment by TelepathicGrunt** [comment]
Take a look at the log itself. They added why it was crashing to it
![image](https://user-images.githubusercontent.com/40846040/109431652-9c2b2400-79d5-11eb-9583-3032b32e86f0.png)

**Comment by Sirttas** [comment]
I realy recommend disabling the feature in issue https://github.com/someaddons/performant_issues/issues/70 as more and more mods encounter problems with it and this kind of warnings will be present in more mods.

**Comment by someaddons** [comment]
the feature in question is actually off by default since quite some months now and it rarely actually caused issues, ppl are just misinformed through cpw misunderstanding what the code does.

**Comment by RogueLogix** [comment]
I am going to note that my warning is a result of actual issues (that are unreproducible without performant) that I believe are caused by what CPW brought up, not the other way around. I rely heavily on the tick events (through Phosphophyllite) for everything (and I mean everything) my mods do, so I have reason to believe that the event modifications CPW mentioned are causing the issues, though I'm not actually sure what exactly is causing the issues.

**Comment by someaddons** [comment]
well normally you'd make a bug report when you're having issues than jumping to conclusion on something I've told in reply was very misinterpreted and is not actually the case. As you'd normally would with about every other mod yours might have an issue with, you're just beeing biased here.

**Comment by TelepathicGrunt** [comment]
Except performant is widely known in the modding community now to be a problem with most mods and is often recommended to be removed first like Optifine when dealing with crashes/issues. Check out Resourceful Bees now looking to add code to tell people to remove performant because performant nukes bee AI extremely badly. 

Performant is like Optifine but worse in mod compat to the point people gave up on it. Doesnt help that performant is closed source and refuses to let anyone PR fixes to it.

**Comment by someaddons** [comment]
ye there for sure is biased hating going around, spread by certain people like you. Performant ofc does have some compat issues, though as with all other mods if you got a compat issue you'd simply report it to the mod. Pretending I dont care or everything is just broken without even creating issue reports is just stupid.

**Comment by RogueLogix** [comment]
There already _was_ an issue report, #70. Before I added the warning I unzipped/decompiled Performant 1.16.2-4-3.30m, latest at the time, and confirmed what CPW was saying. The entirety of com.performant.coremod.event.EventHandlerB looked like something that could easily cause strange and unusual otherwise non-reproducable problems like i saw, along with dataloss and just straight up weird behavior. Consider that, as CPW was saying people do, I tick hundreds or thousands of multiblocks from those events, possibly across multiple worlds and mods. You aren't just pausing a single chunk, or a single tile when that event is paused for me. That event also handles all my multiblock attachment, detachment, assembly and disassembly, so it can *easily* go over 1.8ms/tick, even under normal circumstances. Actually, it can push itself to over 1.8ms/tick avg over the last 64 ticks in a single tick pretty easily with larger multiblocks. I can see in your config that its off by default (btw, at least in this version, the comment says on by default), but *somehow* there were still issues. 

If you want to actually look into the cause of the weird behavior, my mod is open source so you can easily look through its code, https://github.com/BiggerSeries/BiggerSeries for the pair of them. the 0.5.0-alpha.1 files have the latest of my multiblock system in it, which should have the specific bug that caused the multiblock segmentation issues i saw fixed, as i think it was reproduced in a different way, so it should(tm) handle the weird ticking that Performant can do fine. However, it will still pause *all* of them at the same time, maybe even mid tick for different worlds, and could easily cause dataloss due to how i am forced to save things.

**Comment by someaddons** [comment]
yes the event load balancing has been off by default since january, because someone asked me nicely. hey surprise sometimes talking to ppl might be an option? xD So for sure its not the load balancing affecting you, which in the first place would only affect you aswell when the server was already lagging and you were able to get an high avg as mentioned. I dont mind looking into it if I get an actual issue report with some details, what to reproduce and whats failing.

**Comment by RogueLogix** [comment]
Produced in ATM6 1.5.1, the issue that im now actually not sure if its fixed from my end is where a functional reactor would stop working, and based on the multblock data that the player got via my debug tool it appeared to be segmented into multiple sections that didnt merge. The bug i *did* fix had a null controller and wouldn't give any information in debug, so they may actually be different things. I dont know exactly what config was used there, but if the event pausing was off, is there anything else that you know of that could cause weird behavior like that? I dont have exact instructions on how to reproduce it as i never got them, the player had it happen periodically and after removing performant didnt.

If reproduced identically, you will see a reactor that is fully contained within a single chunk looks to be assembled but wont be functional, and may give different construction errors depending on which block you click. Debeefer gives more detailed information on the multiblocks and can show different controller objects for different parts of the multiblock.

**Comment by someaddons** [comment]
hm no the load balancing is the only part where I'd ever touched the events, maybe it could happen if there was throttling due to load balancing to the Tileentity ticks?

**Comment by RogueLogix** [comment]
none of my tile entities tick (wait, thats a lie, one does, its unrelated), all of my ticking is done via those events

**Comment by someaddons** [comment]
ye difficult to tell without reproduction
