### ISSUE TITLE
[1.16.5] Armor stands are unbearably laggy with Performant installed

### ISSUE THREAD

**Issue by iCeParadox64** [someaddons/performant_issues#116]
**Describe the bug**
While performant is installed, armor stands don't move smoothly as entities should. This occurs even when absolutely no other mods are installed, I've even tried tweaking _every single setting_ in the config file, but none of them fix this problem.  
_**[VIDEO HERE](https://streamable.com/9s15c6)**_

**To Reproduce**
1. Install Performant
2. Load into a world
3. Place down an armor stand, immediately see buginess
4. Make armor stand fall, see even more buginess

**Expected behavior**
When placing an armor stand down, it should just... be placed down. Instead, it jitters uncontrollably for a few moments before eventually coming to a standstill.  
When breaking a block below an armor stand, it should fall down smoothly like any other entity. Instead, it moves in slow motion at about a frame a second (for lack of a better description), taking about five seconds for it to fall down a single block.

**Mod version**
v3.30m

**Forge version**  
36.0.46

**Logs**
Here's my log file from the video. Lines 140-145 seem to be of interest.
[latest.log](https://github.com/someaddons/performant_issues/files/6104548/latest.log)

**Comment by BentoGambin** [comment]
Ohhhhhh so it is performant that does that, LOL

**Comment by Paspartout** [comment]
Yeah there seems to be a mixin in the mod which throttles Armor Stand updates/ticks to twice every second. Probably because Armor Stands tend to be laggy? It can be disabled by editing the performant.mixins.json(with e.g. 7zip) in the jar file by removing the line `    "entity.ArmorStandEntityMixin",`.

Would be nice if the author would add a config option for this optimization, since it is quite fun to build amor stand contraptions.

**Comment by someaddons** [comment]
should be fixed in 3.40m
