### ISSUE TITLE
[Feature] Implement config option to disable onChunkUnloaded delay

### ISSUE THREAD

**Issue by KR33PY** [someaddons/performant_issues#118]
This should be configurable since delaying onChunkUnloaded sometimes brings up massive problems: https://github.com/mekanism/Mekanism/issues/7062

**Comment by someaddons** [comment]
I assume you mean unloading tileentities? and there is a config option for it and by default its always false, its an only turn on thing when some mods making a lot of issues with repeatedly calling its unloaded.


`#Requires TELoadBalancing = true. Enables dealing with lag caused by tile entities during chunk unload. This is normally not needed. default = false
TEUnloadLag = false`

**Comment by KR33PY** [comment]
Ah yes, you're right.
I'm talking about TEUnloadLag option and it is indeed configurable, double-checked.
Can confirm that if it's turned on then Mekanism-related issues will arise.

**Comment by someaddons** [comment]
ye its an old do only turn this on if desperate thing, as it will break stuff likely thats why the comment tells you that you don't need it. Could probably remove it aswell these days
