### ISSUE TITLE
Performant exacerbates server "Is server overloaded? Behind xxx ms" notice

### ISSUE THREAD

**Issue by Bidgam** [someaddons/performant_issues#129]
MC 1.16.5, Forge 36.1.2, Performant 3.40m (though the issue has been going since the previous version, 3.30, at least).

Server: Intel 9900k 16GB, standalone

Flying around a new or old world in Creative Mode with the mod installed with any modpack (tested with several, including Valhelsia 3) or set of other mods and after a few minutes the "Is server overloaded? Behind xxx ms" will come up. After a few more minutes it'll continue aggressively every minute or so. This even includes flying over the same terrain to avoid new terrain generation issues.

I suspect this tick lag is caused by other mods (tested this a bit and biome mods have it, as well as biome+entity mods as a collective stress to the server), however, Performant severely exacerbates it. The tick lag 'ms' is higher, ticket lag is more frequent, AND after stopping your character from moving the tick lag still continues indefinitely. This does not happen without Performant.

**Comment by radiomike** [comment]
This sounds like old gen garbage collection causing lag. Was playing valhelsia 3 on a small server and saw this. Basically, the game ran fine until old gen filled up, then the time between old gen collections would become shorter. Using spark and visualvm, it was obvious that the server overloaded messages were the result of these collections. On my server, the old gen collections were easily 3+secs, which would cause that message.
Exploring, loading chunks and especially generating new chunks accelerated the rate old gen filled up considerably. Didn't try without performant, so not sure what difference that would have made. My solution was just to restart the server as soon as possible after the first old gen collection, before the collections got too frequent.

**Comment by Bidgam** [comment]
> This sounds like old gen garbage collection causing lag. Was playing valhelsia 3 on a small server and saw this. Basically, the game ran fine until old gen filled up, then the time between old gen collections would become shorter. Using spark and visualvm, it was obvious that the server overloaded messages were the result of these collections. On my server, the old gen collections were easily 3+secs, which would cause that message.
> 
> Exploring, loading chunks and especially generating new chunks accelerated the rate old gen filled up considerably. Didn't try without performant, so not sure what difference that would have made. My solution was just to restart the server as soon as possible after the first old gen collection, before the collections got too frequent.

It does seem to be a GC connected issue as I ran different GC settings and the tick lag number (how many ms) changed, but the issue still remained unfortunately.

Restarting the server here too does clean it out, but of course it just starts up all over again once you travel around again.

Try without Performant and see if that helps.

**Comment by Bidgam** [comment]
I also should note that it didn't 'seem' like the issue occurred in the Nether or End, but definitely in the Overworld for sure.

**Comment by radiomike** [comment]
> Restarting the server here too does clean it out, but of course it just starts up all over again once you travel around.
> 
> Try without Performant and see if that helps.

To be honest, the occasional reboot, was more than compensated by the low ms per tick. Most of the time, the reboot would be once every couple of days, though occasionally after a couple of hours. Tp'ing around to load every chunk for chocolatefix before an update was one extreme example. 

I also used sparks' `healthreport --memory` command to watch the increase in memory usage over time. It seems like some kind of memory leak as the old gen collections weren't able to clear much of this, hence the repeated old gen collections. Currently playing a different pack, without performant, and not seeing this behaviour. It is a different pack, though and there's lots of other differences. 

> I also should note that it didn't 'seem' like the issue occurred in the Nether or End, but definitely in the Overworld for sure.

I saw this too, either it's not happening there, or the memory usage was increasing at a much lower rate.

**Comment by radiomike** [comment]
Had a bit of time, so ran a couple of tests. A bit anecdotal, but hopefully helpful. 

Basically flying in creative mode on singleplayer in the overworld for a period of time, watching old gen memory usage via `spark gcmonitor`. Did 4 runs.

**Valhelsia 3 -3.2.2 with performant.**
   Over time old gen builds up. There's some fluctuation in size, but gradually the amount in old gen goes up after mixed gc's (went from approx 2GB to 4GB on 7GB instance. Was still growing, but that's where I stopped). Saw one full GC in this test. 
**Valhelsia 3 -3.2.2 without performant**
   Old gen grew a bit initially, but then remains fairly constant. After mixed gc's the amount in old gen returned to approximately the same size (old gen hovered around 2-2.4GB on 7GB instance). There was no full gc seen.
**Just latest performant and spark installed forge 36.1.2. VM size was set to 2GB.**
   Old gen grew, initially hovered around 1GB during the day, once night hit old gen then grew, hitting 1.4GB and causing full gc's.
**Just Spark, as above.**
   Old gen grew initially, but then hovered around 7-800MB. There was no change at night time and no full gc's.

My guess is that performant is cacheing some info, but then not freeing it back up later? Presumably it's per mob related info. It's way more obvious on a modded instance because of the number of different mobs. Staying in one place reduces the speed of the build up because you see less mobs over time. Assuming this is correct, perhaps some limit on the cache size needs to be in place. Probably as a %of vm size, and/or some age limit on data?

**Comment by Bidgam** [comment]
Be sure to also test by flying around back and forth. If you do that, you'll realize that having to restart every hour, or even less, is of course unacceptable. I was getting severe ms tick lag delays every minutes after just 10-20 minutes of flying around. That's unacceptable.

This is what I suspect as well, GC is building up something and Performant is exacerbating the issue. It needs to somehow actually clear out GC or aid it in some way to prevent these ticks from every occurring, or certainly occurring at the rate they are currently. For anyone exploring and the mod being used in modpacks, the mod just isn't useable at this present time.

**Comment by MarioSMB** [comment]
Can confirm this kind of behaviour; it's most certainly memory leaks, in singleplayer it can be horrible (game freezing every few seconds), or on servers tick times will increase as it reaches 100% memory usage and crashes itself. Using default JVM flags, but no other combination has improved the situation.  
Travelling into newly generated chunks does indeed rapidly speed up this process.

**Comment by someaddons** [comment]
^might be fixed in the newest, would be nice if you could do some testing again
