### ISSUE TITLE
Compatibility issue with EvilCraft

### ISSUE THREAD

**Issue by bigenergy** [someaddons/performant_issues#161]
**To Reproduce**
1. Craft an Empty Bowl of Promises in a Crafting Table
2. Craft a Dusted Bowl of Promises in a Crafting Table
3. Infuse a Dusted Bowl of Promises into a Bowl of Promises: Tier 0 in the Blood Infuser
4. Infuse a block of iron into an Iron Promise Acceptor in the Blood Infuser
5. Infuse an Iron Promise Acceptor into a Promise of Tenacity I in the Blood Infuser
6. Craft a Dusted Bowl of Promises in a Crafting Table
7. Load the Promise of Tenacity I into the Blood Infuser
8. Attempt to Infuse a Dusted Bowl of Promises into a Bowl of Promises: Tier 1 in the Blood Infuser.

**Expected behavior**
With a Promise of Tenacity loaded in the Blood Infuser, the Dusted Bowl of Promises should Infuse into a Bowl of Promises: Tier 1, but instead a Bowl of Promises: Tier 0 comes out.

** Mod version **
performant-1.16.2-5-3.66m

** Logs **
No logs

This problem is only with the installed performant
Related https://github.com/CyclopsMC/EvilCraft/issues/847

**Comment by someaddons** [comment]
turning off recipe caching in the config should fix it

**Comment by someaddons** [comment]
I've looked into it and this is probably best resolved by evilcrafting adapting the recipes a bit, as they basically have conflicting recipes for the different tiers wich all are valid and then internally resolve the conflict to use the highest recipe. That behaviour makes performant's cached recipe say "Hey I'm valid for this input" and thus gets returned. I think the best would be to simply have the tier 0 recipe be invalid when crafting tier 1,  by using `==` for the fluid inventory tier on the recipes instead of `<=` at 
https://github.com/CyclopsMC/EvilCraft/blob/14c62ace82d06b605d08ad418fb312ca459e28c4/src/main/java/org/cyclops/evilcraft/core/recipe/type/RecipeBloodInfuser.java

**Comment by someaddons** [comment]
As a workaround disable `cacheRecipes` in the performant config, closing as the mod doesnt seem interested in a solution for their broken recipes.
