### ISSUE TITLE
Double slabs freezing mobs whilst using performant

### ISSUE THREAD

**Issue by h4vok-git** [someaddons/performant_issues#215]
I have discovered a bug when running this mod alongside the double slabs mod when using performant on my server alongside the double slabs mod (DoubleSlabs-1.16-3.5.2) causes mobs to freeze they still collide with the player but cannot move whatsoever even breaking the slabs below them or using water results in the mob still being frozen in mid air as the mob is not affected by gravity. To replicate this issue i made a 3x3 acacia slab platform (the slabs were stacked on eachother resulting in it being a full block in height) and spawned mobs above the area which would result in them freezing. The most consistent way to get this glitch is to throw chicken eggs at the slabs which yields a 100% reproducible result. This issue is not present when running the double slabs mod on my server without performant. NOTE: this effect can be seen by other players on multiplayer aswell.

I have not tested a new version of double slabs yet but will update this thread if this issue is resolved on a later version.

** Mod version **
using forge 36.2.20, (1.16.5 multiplayer server) performant-1.16.2-5-3.81m

![Screenshot 2021-06-11 213219](https://user-images.githubusercontent.com/84686040/148284535-a551925a-5a89-475a-8e63-e1cbdb6223bc.png)

**Comment by h4vok-git** [comment]
this issue is still prevalent on the latest version of double slabs

https://user-images.githubusercontent.com/84686040/148287946-7694b66a-ad3d-467e-87f1-9ff79ea79264.mp4

.

**Comment by someaddons** [comment]
Found the cause, double slabs injects a bad value, but it only surfaces with performant due to performant changing the movement timing a little due to multithreading. 

Cause is that double slabs returns 0d as default value for the slipperiness calc here:
https://github.com/CJMinecraft01/DoubleSlabs/blob/e908bfffb0e6680d61f7ad86364565c5da901812/src/main/java/cjminecraft/doubleslabs/common/blocks/DynamicSlabBlock.java#L355
 which then later is used by vanilla for this part:

![image](https://user-images.githubusercontent.com/38401808/148431848-d6539d2c-b61b-48e9-b97b-d54250ab2d81.png)

which then causes a division by ~zero with a NaN return value for the movement.

I'm adding a "fix" to performant, which corrects from such a bad value state, but double slabs probably should also fix that they default to 0d slipperiness instead of the default vanilla uses of 0.6d.
