### ISSUE TITLE
[Bug]: The CONFIG button added by https://www.curseforge.com/minecraft/mc-mods/configured stopped working for ALL of your mods.

### ISSUE THREAD

**Issue by Minebrah** [someaddons/performant_issues#269]
### Describe the bug you're experiencing

I've been playing with a lot of your mods for a very long time now and am a huge fan. However recently I updated some mods and for whatever reason now the Config button, where I would click to configure all of your mods, just stopped working. I can't configure any of your mods and haven't been able to get any help from the CONFIGURED mod maker.  

![Screenshot (3)](https://user-images.githubusercontent.com/128096529/227755770-db809756-ea27-40de-8d74-72c4497a493a.png)

[debug.log](https://github.com/someaddons/performant_issues/files/11070801/debug.log)

### Reproducability

I'm using almost all of your forge 1.19.2 mods including the paid updated version of Performant from your Patreon. I'm saying this because theres no 1.19.2 version on the versions listed below. 

The Configured button that allows me to configure your mod belongs to MrCrayfish and can be found here. https://www.curseforge.com/minecraft/mc-mods/configured

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/Minebrah/99fcf5d3ce1f1f10162b1dde47151bf7

**Comment by someaddons** [comment]
Hi, performants configs and most of my other mods configs did not change recently, so they should be working as before. Most likely the new configured version just has some kind of issue.
In any case I recommend changing config values in the config files itself instead of via ingame GUI, since there are many values which cannot apply without a restart anyways and may even get reset when editing while running the game.

**Comment by Minebrah** [comment]
Ok thanks for the reply I'll try giving that a shot.
