### ISSUE TITLE
[mc1.15.2] problem with advanced mining dimension #73

### ISSUE THREAD

**Issue by someaddons** [someaddons/performant_issues#3]
**Describe the bug**
so... in first time i saw bug in the modpack, i mining in the mining dimension when i tried to retun to overworld, i suddenly start dying. After troubleshooting i found out only with performant causing this problem

when created a new profile mc 1.15.2 with same mods and forge, created a new world after tried enter to dimension but appearing fatal error with biome decoration, but if i turn off performant, get in to dimension and get out of there and when turn on performan this fatal error does not appear anymore.

first time i saw that on HR: new begginings after i updated all mods
tested on new profile with only: advanced mining dimension, mixinbootstrap and performant

**To Reproduce**
on new profile first time:
1. place block
2. activate the block
3. see error

in the modpack or after some manipulation on new profile:
1. place block
2. activate the block
3. walk a little
4. try go back to the overworld
5. and suffocate in a wall for no reason

**Expected behavior**
teleporting to the mining dimension and back with out problem 

**Screenshots**
i dont have a screenshots but i have [video](https://youtu.be/h2EkAQJw16E) what happening on new profile mc

** Mod version **
1. forge 31.2.30
2. performant 3.10m
3. mixinboostrap 1.0.3
4. advanced mining dimension 1.0.4 and beta 1.0.6

[log](https://gist.github.com/joinmod/ed84a209b6c9e7f435c78dc78d386359) with fatal error from new profile
[log](https://gist.github.com/joinmod/fb874143aa12efe750196d334006fb1e) from modpack with disabled all mods except those 3 mods

P.S 
advanced mining dimension developer already knows this problem and ask to me report here aswell because he say this is performant problem

**Comment by ClaudiusMinimus** [comment]
I too am having this issue with my new mod pack [Survival in Chaos](https://www.curseforge.com/minecraft/modpacks/survival-in-chaos). I use the Advanced Mining Dimension as well.

**Comment by ClaudiusMinimus** [comment]
I forgot to add that I also tried updating to performant-1.15-3.11m and the issue persists. It should be noted that I only see this issue if Performant is installed on a server. Singleplayer worlds seem unaffected.

**Comment by switch263** [comment]
I hit this in the latest Plunger pack as well - disabling performant on the server resolved it for us as well.

**Comment by gerb82** [comment]
I have a hypothesis
It might be completely stupid
But it just seems too plausible to completely ignore

Logically, it sounds like the suffocation damage is caused by the position the player is teleported into initially being inside a wall
We've also done some experimentation with people who have some lag when loading a new dimension, and it appears that they take damage until they move even a tiny bit, at which point it stops
However, they can only start moving once they fully load the area

So my hypothesis is that either the position is handled a bit too late in the loading process, or some tweak to the collision algorithm is having some unexpected behavior with a player entity that is frozen in place while teleporting
As such, a potential fix might be to lock the player position before sending the rest of the packets, or to mark a player that's loading in as invulnerable to collision

Again, just my two cents. Obviously can't tell too much, as at the end of the day, I only see the results of the code. But hopefully that's enough to at least help figuring it out
