### ISSUE TITLE
Question regarding code on 1.12

### ISSUE THREAD

**Issue by Sunconure11** [someaddons/performant_issues#9]
I noticed there was a bug between this mod and Bewitchment, but as your mod is closed source, I cannot roll out any kind of fix. What can be done here? I’m aware 1.12 support is over, but I would at least like to know how this mod is messing with the cauldron, as with this mod installed, the cauldron does not work at all (it acts as though an item has been placed twice, causing any recipes in it to fail.)

https://github.com/Um-Mitternacht/Bewitchment/blob/1.12.2/src/main/java/com/bewitchment/common/block/tile/entity/TileEntityWitchesCauldron.java

**Comment by someaddons** [comment]
1.12 has some collision caching, that might be why its placed twice. Can just tell them to remove it, my 1.12 version is very outdated.

**Comment by someaddons** [comment]
1.12 is archieved now just tell those few ppl actually using it to uninstall when they got issues

**Comment by ZacDelves** [comment]
@someaddons forgive me, but i must share this with you xP I think you aren't giving yourself enough credit here. Those users would be amiss to abandon performant 👍 :)

"Rickyroo615Today at 8:34 AM
hey, i love the modpack, exploring is fun, but i only have one major problem
whenever i try to fight somthing, my enemy constantly just sits there, then lurches forward, and i deal no damage
its to the point where i have to use spears so i dont get lag- killed
and defending or fighting is more of a chore now, then a machanic
got any suggestions?

ZacToday at 8:45 AM
what is your server hardware @Rickyroo615
Rickyroo615Today at 8:46 AM
i play by myself
im not sure about hardware
i got a prebuilt
ZacToday at 8:47 AM
hmm thats strange, try capping your fps in the ingame options so that unused frames go towards ticks per second instead
and try using this https://www.curseforge.com/minecraft/mc-mods/performant
Rickyroo615Today at 8:49 AM
alright, ill try it
thanks by the way
i love this game but i stopped because combat was so laggy
Rickyroo615Today at 9:25 AM
It works!
ZacToday at 9:26 AM
putting on the mod performant solved a massive and consistent issue entirely?
hory mory
really? or is it just a decent bit improved from how it was?
Rickyroo615Today at 9:34 AM
i fought a mob and it didnt lag one bit!"

430,000 ppl have downloaded this pack (rebirth of the night) since its release later last year. The mod is definitely being considered to be added now.

I just thank you a lot for having made this mod, and potentially making others able to play a prime MC experience that hadn't before. And i hope you enjoy this lil success story. Not sure why the downloads are low on 1.12.2 version of performant but most big mods are still on 1.12.2 and many multi version ones like minecolonies are still by far the most dl'd on 1.12.2. Minecraft is a game with a lot of flaws as you know, and many of those are gameplay flaws, so unfortunately the large codebase of 1.12.2 is required if anyone wants to not have to suspend disbelief and just "take the game for what it is" to enjoy it but rather, take the game for what its always meant to have been
